# Algoritmos de optimización - Seminario

Nombre y Apellidos:   
* Andrés Gómez
* Iván Cañón


Url: https://github.com/Icanongonz/SEMINARIO/blob/colab/Seminario_Algoritmos.ipynb<br>
Problema: **Sesiones de doblaje**

Descripción del problema: Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible                                        

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




## Cálculo del número de planificaciones posibles

El conjunto de datos contiene 30 tomas y existe una única restricción temporal: no se pueden grabar más de 6 tomas por día.

Para calcular cuántas planificaciones son posibles, se considera que cada toma puede asignarse a un día de grabación, siempre respetando el límite de 6 tomas por jornada.

Por ejemplo, las 30 tomas podrían organizarse de muchas formas distintas:

- 5 días con 6 tomas cada uno.
- 6 días con una distribución de 6, 6, 6, 6, 5 y 1 tomas.
- 7 días con diferentes repartos, siempre que ningún día supere las 6 tomas.
- etc...

Cada una de estas distribuciones genera a su vez numerosas combinaciones, ya que las tomas son diferentes y pueden agruparse de múltiples maneras.

El número de planificaciones posibles se calcula mediante la siguiente relación recursiva:

$$
f(n)=\sum_{k=1}^{6}\binom{n}{k}f(n-k)
$$

donde:

- $n$ representa el número de tomas pendientes de asignar.
- $k$ representa el número de tomas asignadas al siguiente día de grabación.
- $\binom{n}{k}$ indica el número de formas de seleccionar $k$ tomas entre las $n$ disponibles.

Esta expresión considera todas las posibilidades válidas de asignar entre 1 y 6 tomas por jornada hasta completar la planificación de las 30 tomas.

El resultado es:

11.400.192.964.820.634.141.875.720.888.504.025.088

Es decir, aproximadamente:

1,14 × 10^37

Esto representa un número extremadamente grande de planificaciones posibles, por lo que evaluar todas las soluciones de forma exhaustiva resulta inviable.

Este valor muestra que el espacio de búsqueda es extremadamente grande, por lo que resulta inviable evaluar todas las soluciones de forma exhaustiva. Por este motivo, en problemas de planificación como el doblaje de películas se emplean técnicas de optimización para encontrar una solución de bajo coste sin necesidad de analizar todas las posibilidades.

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)

Respuesta:

* La estructura elegida para los datos del problema es una matriz de *t* tomas x *a* actores, en cada elemento (toma, actor) un *1* o *0* según si el actor tiene participación o no. Es una estructura simple que nos permitirá calcular los gastos en base a los actores involucrados en las tomas.

* La estructura para representar la solución es un array de *t* tomas, donde cada elemento representa el día que ser realizará la misma. Es una estructura que nos permitirá hacer diferentes asignaciones de los días sin complejidad, cambiar los días de una toma, intercambiarlos, etc. Calcular la limitación de máximo 6 tomas por días es una operación sencilla de acumular las ocurrencias de cada día.

Según el modelo para el espacio de soluciones<br>
¿Cual es la función objetivo?

Respuesta:

El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible.

(*)¿Es un problema de maximización o minimización?

Respuesta:

Es un problema de minimización, se busca el menor gasto posible.

### importación de librerías

In [ ]:
import numpy as np
import pandas as pd
import itertools

### Carga de datos del problema

In [ ]:
# recuperar las tomas/actor desde csv
df = pd.read_csv('Datos problema doblaje (30 tomas, 10 actores).csv', delimiter=';')
df = df.drop('Toma', axis=1)
# generar la matriz toma x actor
problema = df.to_numpy()
print(problema)

[[1 1 1 1 1 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 1 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]]


### Funciones Compartidas

In [ ]:
# costo para penalizar las soluciones que no cumplen la restricción
COSTO_RESTRICCION = 10000

# Calcula el costo de una solución.
def calcular_costo(problema, solucion):
    '''
    Calcula el costo de una solución.
    Si se exceden las 6 tomas en un mismo día, habrá un costo extra COSTO_RESTRICCION para penalizar la solución
    '''
    costo = 0

    # la cantidad de dias maxima es igual a la cantidad de tomas (es en el caso de que se haga una toma por dia)
    tomas = len(solucion)

    # agrupar las tomas por dia
    dias = [[] for i in range(tomas)]
    for t in range(tomas):
        d = solucion[t]
        dias[d].append(t)

    # calcular el costo por dia
    for d in range(len(dias)):
        # actores que van a participar en las tomas de ese dia
        actores = []
        # recorremos las tomas de ese día
        for t in dias[d]:
            for a in range(problema.shape[1]):
                if problema[t, a] == 1:
                    actores.append(a)
        # calculamos el costo en base a la cantidad de actores
        actores = set(actores)
        costo += len(actores)

    # RESTRICCION: calcular un costo muy alto si se excede el maximo de 6 tomas
    for d in range(tomas):
        if len(dias[d]) > 6:
            costo += COSTO_RESTRICCION

    return costo

In [ ]:
# función para imprimir el detalle de tomas por cada día
def imprimir_solucion(problema, solucion):
    dias = {}
    # recorremos las tomas y las agrupamos por dia
    for i in range(len(solucion)):
        if not solucion[i] in dias:
            dias[solucion[i]] = []
        dias[solucion[i]].append(i + 1) # así las tomas empiezan en 1
    # listamos las tomas por cada dia
    tomas = list(dias.values())
    for i in range(len(tomas)):
        # actores que van a participar en las tomas de ese dia
        actores = []
        # recorremos las tomas de ese día
        for t in tomas[i]:
            for a in range(problema.shape[1]):
                if problema[t-1, a] == 1: # t-1 porque las tomas ahora arrancan en 1
                    actores.append(a + 1) # asi los actores empiezan en 1
        actores = list(set(actores))
        print(f"día {i+1}: Tomas = {tomas[i]}, Actores = {actores} ({len(actores)})")
    print(f"Costo de la solucion: { calcular_costo(problema, solucion) }")

Diseña un algoritmo para resolver el problema por fuerza bruta

### Algoritmo por fuerza bruta

In [ ]:
MEJOR_COSTE = float("inf")
MEJOR_PLANIFICACION = None

#Número de actores que deben asistir ese día.
def coste_dia(tomas_dia):
    actores_presentes = np.any(problema[list(tomas_dia)], axis=0)
    return np.sum(actores_presentes)

#Cálculo de costo para algoritmo de fuerza bruta
def coste_planificacion(planificacion):
    return sum(coste_dia(dia) for dia in planificacion)

def fuerza_bruta(tomas_restantes, planificacion_actual):
    global MEJOR_COSTE
    global MEJOR_PLANIFICACION

    if len(tomas_restantes) == 0:

        coste = coste_planificacion(planificacion_actual)

        if coste < MEJOR_COSTE:
            MEJOR_COSTE = coste
            MEJOR_PLANIFICACION = [dia[:] for dia in planificacion_actual]

        return

    lista = list(tomas_restantes)

    for tam in range(1, min(6, len(lista)) + 1):

        for grupo in itertools.combinations(lista, tam):

            restantes = tomas_restantes - set(grupo)
            planificacion_actual.append(list(grupo))
            fuerza_bruta(restantes, planificacion_actual)
            planificacion_actual.pop()


num_tomas = len(problema)

fuerza_bruta(set(range(num_tomas)), [])

print("Mejor coste:", MEJOR_COSTE)
print("Mejor planificación:")
for dia, tomas in enumerate(MEJOR_PLANIFICACION, start=1):
    print(f"Día {dia}: {tomas}")

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

La complejidad temporal del algoritmo es exponencial. Esto se debe a que explora todas las posibles agrupaciones de las tomas en jornadas de grabación, generando un árbol de búsqueda cuyo número de nodos crece de forma muy rápida al aumentar el número de tomas.

Por este motivo, la complejidad puede expresarse como:

$$
T(n)=O(c^n)
$$

donde $n$ representa el número de tomas y $c$ es una constante mayor que 1.

En consecuencia, el tiempo de ejecución aumenta exponencialmente con el tamaño del problema, haciendo inviable la aplicación de fuerza bruta para instancias de gran tamaño.

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

### Algoritmo Genético

In [ ]:
#Genera una poblacion inicial de soluciones de tamaño N.
def generar_poblacion(problema,N):
    return [np.random.randint(0, problema.shape[0], problema.shape[0]) for _ in range(N)]

In [ ]:
#Evalua la población y devuelve el mejor individuo
def Evaluar_Poblacion(poblacion, problem):
    solucion = None
    costo = np.iinfo(np.int32).max
    for s in poblacion:
        c = calcular_costo(problema, s)
        if c < costo:
            solucion = s
            costo = c
    return solucion, costo

In [ ]:
# Funcion de cruce. Recibe una poblacion(lista de soluciones) y devuelve la población ampliada con los hijos.
# Todos los individuos de la población son selecionados para el cruce(si la población es par)
def Cruzar(poblacion, problem, mutacion):
    soluciones = []
    soluciones += poblacion
    # los desordenamos para que el cruce sea al azar
    np.random.shuffle(poblacion)
    for p in range(0, len(poblacion) - 1, 2):
        hijo = Descendencia([poblacion[p], poblacion[p+1]], problem, mutacion)
        soluciones.append(hijo)
    return soluciones

In [ ]:
# Funcion para generar hijos a partir de 2 padres:
# Se elige el metodo de 1-punto de corte
# Se aplica mutacion
def Descendencia(padres, problem, mutacion):
    # Se elige el metodo de 1-punto de corte
    punto = np.random.randint(0, len(padres[0]))
    hijo = np.concatenate([padres[0][:punto], padres[1][punto:]])
    # se aplica mutacion
    hijo = Mutar(hijo, mutacion)
    return hijo

In [ ]:
# Funcion de mutación. Al azar se aplica alguna de estas operaciones:
# - se elije una toma al azar y se le asigna un día al azar
# - se intercambian los dias de dos tomas
# Se hace mutaciones mutacion% de las veces, si no hay mutacion se retorna None
def Mutar(solucion, mutacion):
    # mutacion solo el % de la veces
    if mutacion > np.random.uniform():
        operacion = np.random.randint(0, 2)
        if operacion == 0:
            # se elije una toma al azar y se le asigna un día al azar
            toma = np.random.randint(0, len(solucion))
            solucion[toma] = np.random.randint(0, len(solucion))
        elif operacion == 1:
            # se intercambian los dias de dos tomas
            t1, t2 = np.random.randint(0, len(solucion)), np.random.randint(0, len(solucion))
            solucion[t1], solucion[t2] = solucion[t2], solucion[t1]
    return solucion

In [ ]:
#Funcion de seleccion de la población. Recibe como parametro una poblacion y
# devuelve una poblacion a la que se ha eliminado individuos poco aptos (fitness alto) y para mantener una poblacion estable de N individuos
# Se tiene en cuenta el porcentaje elitismo pasado como parametro
# Para los individuos que no son de la elite, se tomará un 10% al azar (asi damos chance a sobrevivir a uno muy malo y tenemos mas diversidad)
# y se usará una selección de ruleta(proporcional a su fitness) con el resto.
def Seleccionar(poblacion, problema, N, elitismo):
    soluciones = []

    # calcular los costos y ordenar
    costos = [calcular_costo(problema, solucion) for solucion in poblacion]
    ranking = zip(poblacion, costos)
    ranking = sorted(ranking, key=lambda item: item[1])

    # salvamos a la elite
    elitismo = min(int(len(ranking) * elitismo), N)
    for i in range(elitismo):
        s = ranking.pop(0)
        soluciones.append(s[0])

    # se salvan el 10% al azar
    salvar = min(int(len(ranking) * .1), N - len(soluciones))
    for i in range(salvar):
        s = np.random.randint(0, len(ranking))
        s = ranking.pop(s)
        soluciones.append(s[0])

    #vamos salvando hasta llegar a N
    # se usará una selección de ruleta(proporcional a su fitness) con el resto.
    max_costo = ranking[-1][1]
    min_costo = ranking[0][1]
    while(len(ranking) > 0 and len(soluciones) < N):
        keep = []
        for i in range(len(ranking)):
            s = ranking[i]
            prob = (s[1] - min_costo) / (max_costo - min_costo)
            if prob < np.random.uniform():
                # se salva
                soluciones.append(s[0])
                if (len(soluciones) == N):
                    break
            else:
                # sigue participando
                keep.append(s)
        ranking = keep

    return soluciones


In [ ]:
#Funcion principal del algoritmo genetico
#######################################################3
def algoritmo_genetico(problema=problema, N=100, mutacion=.15, elitismo=.1, generaciones=100):
    # problem = datos del problema
    # N = Tamaño de la población
    # mutacion = probabilidad de una mutación
    # elitismo = porcion de la mejor poblacion a mantener
    # generaciones = nº de generaciones a generar para finalizar

    #Genera la poblacion inicial
    poblacion = generar_poblacion(problema, N)

    #Inicializamos valores para la mejor solucion
    (mejor_solucion, mejor_costo) = Evaluar_Poblacion(poblacion, problema)

    #Condicion de parada
    parar = False
    n=0
    #Inciamos el cliclo de generaciones
    while(parar == False) :
        #Cruce de la poblacion(incluye mutación)
        poblacion = Cruzar(poblacion, problema, mutacion)

        #Seleccionamos la población
        poblacion = Seleccionar(poblacion, problema, N, elitismo)

        #Evaluamos la nueva población
        (mejor_solucion, mejor_costo) = Evaluar_Poblacion(poblacion, problema)

        #print("Generacion #", n, "\nLa mejor solución es:" , mejor_solucion, "\ncon costo " , mejor_costo, "\n")

        #Numero de generaciones. Criterio de parada
        if n==generaciones:
            parar = True
        n +=1

    return mejor_solucion

In [ ]:
# obtener una solucion usando algoritmo genetico
solucion_genetico = algoritmo_genetico(problema=problema,N=1000, mutacion=.3, elitismo=.4, generaciones=200)
# finalmente imprimir
imprimir_solucion(problema, solucion_genetico)

día 1: Tomas = [1, 4, 5, 7, 11, 13], Actores = [1, 2, 3, 4, 5, 7, 8] (7)
día 2: Tomas = [2, 14, 18, 22, 24, 29], Actores = [1, 2, 3, 4, 5, 6] (6)
día 3: Tomas = [3, 6, 9, 15, 27, 30], Actores = [1, 2, 4, 5, 7] (5)
día 4: Tomas = [8, 10, 12, 20, 21, 26], Actores = [1, 2, 3, 4, 5, 6, 8, 9] (8)
día 5: Tomas = [16, 17, 19, 23, 25, 28], Actores = [1, 2, 3, 4, 10] (5)
Costo de la solucion: 31


(*)Calcula la complejidad del algoritmo

Respuesta

## Análisis de la complejidad del algoritmo genético

### Introducción

A diferencia de la fuerza bruta, que intenta evaluar todas las soluciones posibles, el algoritmo genético trabaja únicamente con un conjunto de soluciones candidatas. Estas soluciones evolucionan generación tras generación mediante operaciones de selección, cruce y mutación.

Gracias a este enfoque, el algoritmo puede encontrar buenas soluciones sin necesidad de recorrer todo el espacio de búsqueda, lo que reduce considerablemente el tiempo de ejecución.

Para analizar su complejidad utilizaremos las siguientes variables:

- **n**: número de tomas.
- **N**: tamaño de la población.
- **G**: número de generaciones.
- **C(n)**: coste de evaluar una solución.

En este trabajo:

- n = 30 tomas.
- N = 1000 individuos.
- G = 200 generaciones.

<br>

La población inicial está formada por N individuos y cada individuo contiene información para las n tomas del problema.

Por tanto, la creación de la población requiere:

$$
O(N \cdot n)
$$

operaciones.

<br>

Para conocer qué individuos son mejores, es necesario calcular el coste de cada uno de ellos.

Como se evalúan los N individuos de la población, el coste de esta fase es:

$$
O(N \cdot C(n))
$$

Esta operación se repite en cada generación del algoritmo.

<br>

Durante el cruce se generan nuevos individuos combinando información de dos padres. Como se trabaja con vectores de longitud n, el coste total de esta operación es aproximadamente:

$$
O(N \cdot n)
$$

La mutación consiste únicamente en modificar una o dos posiciones de una solución, por lo que su coste es muy pequeño y puede considerarse constante:

$$
O(1)
$$

<br>

Una vez generados los nuevos individuos, el algoritmo debe decidir cuáles continúan formando parte de la población.

Para ello se calculan los costes, se ordenan las soluciones y se aplican distintos criterios de selección.

Esta fase es la más costosa del algoritmo y puede alcanzar aproximadamente:

$$
O(N^2)
$$

en el peor caso.

<br>

Teniendo en cuenta todas las fases anteriores, el coste de una generación puede aproximarse mediante:

$$
O(N^2 + N \cdot C(n))
$$

<br>

Como el proceso se repite durante G generaciones, la complejidad total es:

$$
O(G \cdot (N^2 + N \cdot C(n)))
$$

En este problema, la evaluación de una solución depende del número de tomas, por lo que puede considerarse:

$$
C(n)=O(n)
$$

Sustituyendo este valor obtenemos:

$$
O(G \cdot (N^2 + N \cdot n))
$$

Además, como el tamaño de la población es mucho mayor que el número de tomas (1000 frente a 30), el término dominante es:

$$
O(G \cdot N^2)
$$

<br>

Con los parámetros utilizados:

- N = 1000 individuos.
- G = 200 generaciones.

el algoritmo evalúa aproximadamente 200.000 soluciones a lo largo de toda la ejecución.

Aunque sigue siendo una cantidad considerable, es muy pequeña comparada con los más de:

$$
1,14 \times 10^{37}
$$

planes de grabación posibles que tendría que analizar un algoritmo de fuerza bruta.


Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

### Generación de juego de datos

In [ ]:
# Función que valida que un problema esté bien definido
def validar_problema(problema):
    if problema.shape[0] <= 1:
        return False
    if problema.shape[1] <= 1:
        return False

    # todas las tomas tienen que tener al menos un actor
    for t in range(problema.shape[0]):
        actores = problema[t].sum()
        if actores == 0:
            return False

    # todos las actores tienen que participar en al menos una toma
    for a in range(problema.shape[1]):
        tomas = problema[:,a].sum()
        if tomas == 0:
            return False

    return True

In [ ]:
# Función que genera un problema aleatorio, se requiere la cantidad de tomas y la cantidad de actores
def generar_problema(tomas=30, actores=10):
    if tomas <= 1:
        raise Exception("se requieren al menos 2 tomas")
    if actores <= 1:
        raise Exception("se requieren al menos 2 actores")

    while True:
        # generamos la matriz aleatoria tomas x actores
        problema = np.random.randint(0, 2, (tomas, actores))
        # verificamos que sea un problema válido
        if validar_problema(problema):
            return problema

In [ ]:
problema_aleatorio = generar_problema()
print(problema_aleatorio)

[[1 1 0 1 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 1 1 1]
 [1 1 1 1 0 1 0 1 0 1]
 [1 0 1 1 0 0 1 0 1 0]
 [0 0 1 0 1 1 1 1 1 1]
 [0 1 0 1 1 1 0 0 0 1]
 [0 0 1 0 1 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 1 1]
 [1 1 0 0 0 1 0 0 0 1]
 [1 1 0 1 0 1 0 0 0 0]
 [0 1 0 1 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [1 0 1 1 1 0 0 1 0 0]
 [0 0 0 1 0 1 0 1 0 0]
 [0 0 0 1 1 1 1 1 0 0]
 [0 1 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 0 1]
 [1 0 0 1 0 0 0 0 0 1]
 [1 1 1 0 0 0 1 1 0 0]
 [1 0 0 0 1 0 1 0 0 0]
 [1 0 1 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 0 0]
 [1 0 0 1 1 1 1 1 0 0]
 [1 1 1 1 1 0 1 1 0 0]
 [1 1 0 1 0 1 0 0 1 0]
 [1 1 0 0 0 1 0 0 0 0]
 [0 0 1 1 0 1 1 1 0 0]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 1 1 1 0 1 0 1 0 1]]


Aplica el algoritmo al juego de datos generado

In [ ]:
# obtener una solucion usando algoritmo genetico para el problema aletorio
solucion_genetico_aleatorio = algoritmo_genetico(problema=problema_aleatorio,N=1000, mutacion=.3, elitismo=.4, generaciones=200)
# finalmente imprimir
imprimir_solucion(problema_aleatorio, solucion_genetico_aleatorio)

día 1: Tomas = [1, 3, 12, 18, 25, 30], Actores = [1, 2, 3, 4, 6, 8, 9, 10] (8)
día 2: Tomas = [2, 5, 8, 21, 23, 24], Actores = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] (10)
día 3: Tomas = [4, 7, 11, 15, 16, 19], Actores = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] (10)
día 4: Tomas = [6, 13, 17, 20, 22, 27], Actores = [1, 2, 3, 4, 5, 6, 7, 8, 10] (9)
día 5: Tomas = [9, 10, 14, 26, 28, 29], Actores = [1, 2, 4, 6, 8, 9, 10] (7)
Costo de la solucion: 44


Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta

## Líneas futuras de trabajo

Aunque el algoritmo genético obtiene buenos resultados para el tamaño del problema estudiado, existen varias formas de seguir mejorándolo.

Una posible línea de trabajo sería probar distintos valores de población, mutación o número de generaciones para comprobar si es posible encontrar soluciones de mejor calidad o reducir el tiempo de ejecución.

También sería interesante comparar los resultados obtenidos con otros métodos de optimización, como búsqueda tabú, recocido simulado o algoritmos voraces, para analizar cuál se adapta mejor a este problema.

Además, podría estudiarse el comportamiento del algoritmo en problemas de mayor tamaño. Por ejemplo, aumentando el número de tomas o el número de actores. En estos casos el espacio de búsqueda crecería considerablemente y sería necesario comprobar si el algoritmo sigue ofreciendo buenos resultados en tiempos razonables.

En ese caso, la paralelización del algoritmo representa una alternativa interesante para reducir los tiempos de ejecución. Dado que la evaluación de los individuos de la población es independiente, varias soluciones podrían analizarse de forma simultánea utilizando varios núcleos del procesador o incluso varias máquinas.

Esto permitiría aumentar el número de individuos o generaciones exploradas sin incrementar proporcionalmente el tiempo necesario para obtener una solución.

Como forma de complicar el problema, podría hacerse más realista añadiendo nuevas restricciones, como:

- Actores con disponibilidad limitada.
- Diferentes costes según el actor.
- Restricciones horarias de grabación.
- Costes asociados al uso del estudio.
- Limitaciones en el número de horas de trabajo al día.

Por último, sería interesante comparar las soluciones obtenidas por el algoritmo genético con las de métodos exactos en problemas pequeños. De esta forma se podría evaluar hasta qué punto las soluciones encontradas se aproximan a la solución óptima.